const admin = require('../config/firebase');

// Utility to get the Firebase API Key
const getApiKey = () => process.env.FIREBASE_API_KEY;

// Register a new user with email and password
exports.register = async (req, res) => {
  const { email, password, displayName } = req.body;

  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required' });
  }

  try {
    const apiKey = getApiKey();
    if (!apiKey) {
      return res.status(500).json({ error: 'Server misconfiguration: FIREBASE_API_KEY is missing' });
    }

    // 1. Create the user in Firebase Auth via REST API to get the ID Token immediately
    const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email,
        password,
        returnSecureToken: true
      })
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('Firebase Auth registration error details:', data.error);
      const errorMessage = data.error?.message || 'Registration failed';
      return res.status(response.status).json({ error: errorMessage });
    }

    // Optional: Update user's display name using Firebase Admin
    if (displayName) {
      await admin.auth().updateUser(data.localId, { displayName });
    }

    // Return the user data and the JWT (idToken)
    res.status(201).json({
      message: 'User registered successfully',
      user: {
        uid: data.localId,
        email: data.email,
        displayName: displayName || null
      },
      token: data.idToken,
      expiresIn: data.expiresIn
    });
  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Login an existing user with email and password
exports.login = async (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required' });
  }

  try {
    const apiKey = getApiKey();
    if (!apiKey) {
      return res.status(500).json({ error: 'Server misconfiguration: FIREBASE_API_KEY is missing' });
    }

    // Call Firebase Auth REST API to sign in the user
    const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email,
        password,
        returnSecureToken: true
      })
    });

    const data = await response.json();

    if (!response.ok) {
      return res.status(response.status).json({ error: data.error.message || 'Login failed' });
    }

    // We can also fetch additional user detail via Admin SDK if necessary 
    // const userRecord = await admin.auth().getUser(data.localId);

    res.status(200).json({
      message: 'Login successful',
      user: {
        uid: data.localId,
        email: data.email,
        displayName: data.displayName
      },
      token: data.idToken,
      expiresIn: data.expiresIn
    });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// Google Sign-In Verification Endpoint
// Expected to receive an ID Token generated by Firebase Client SDK on the frontend
exports.googleSignIn = async (req, res) => {
  const { idToken } = req.body;

  if (!idToken) {
    return res.status(400).json({ error: 'idToken is required' });
  }

  try {
    // Verify the identity of the user
    const decodedToken = await admin.auth().verifyIdToken(idToken);
    
    // The user is authenticated. 
    // Here you would typically check if the user exists in your own database (e.g., MongoDB, PostgreSQL)
    // If not, you could create a new user record for them.
    
    res.status(200).json({
      message: 'Google Sign-In successful',
      user: {
        uid: decodedToken.uid,
        email: decodedToken.email,
        name: decodedToken.name,
        picture: decodedToken.picture
      },
      // Since the frontend already has an ID token, you may simply return success 
      // or issue your own custom backend token here. We will just return the decoded info.
      // The frontend can continue to pass the Firebase idToken in the Authorization header.
    });

  } catch (error) {
    console.error('Google Sign-In error:', error);
    res.status(401).json({ error: 'Invalid or expired token' });
  }
};
